name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.3'
        
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/*.xcodeproj', '**/*.xcworkspace') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
          
    - name: Install dependencies
      run: |
        # Add any dependency installation commands here if needed
        # For example, if using CocoaPods:
        # pod install
        # Or if using Swift Package Manager, dependencies are resolved automatically
        echo "Installing dependencies..."
        
    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
          clean build test \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          | xcpretty --color --report junit --output build/reports/junit.xml
          
    - name: Run Unit Tests
      run: |
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
          test -only-testing:BankAppTests \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          | xcpretty --color
          
    - name: Run UI Tests
      run: |
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
          test -only-testing:BankAppUITests \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          | xcpretty --color
          
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: build/reports/
        
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports
        path: ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
        
  build:
    name: Build
    runs-on: macos-latest
    needs: test
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.3'
        
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/*.xcodeproj', '**/*.xcworkspace') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
          
    - name: Build for Release
      run: |
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
          clean build \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          | xcpretty --color
