name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  XCODE_VERSION: '16.2'
  IOS_SIMULATOR_VERSION: '18.2'
  DERIVED_DATA_PATH: ~/Library/Developer/Xcode/DerivedData

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
        
    - name: Show Xcode Version
      run: |
        xcodebuild -version
        xcrun simctl list devicetypes
        
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ${{ env.DERIVED_DATA_PATH }}
        key: ${{ runner.os }}-xcode-${{ env.XCODE_VERSION }}-derived-data-${{ hashFiles('**/BankApp.xcodeproj/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-${{ env.XCODE_VERSION }}-derived-data-
          
    - name: Create Build Directory
      run: mkdir -p build/reports
      
    - name: List Available Simulators
      run: xcrun simctl list devices available
      
    - name: Fix Deployment Target
      run: |
        cd Bank
        # Update deployment target in project settings to match simulator version
        # This fixes the iOS 18.4 vs 18.2 mismatch
        sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 18.4/IPHONEOS_DEPLOYMENT_TARGET = 18.2/g' BankApp.xcodeproj/project.pbxproj || true
        echo "Updated deployment target to iOS 18.2"
        
    - name: Clean Build Folder
      run: |
        cd Bank
        rm -rf ${{ env.DERIVED_DATA_PATH }}
        
    - name: Resolve Package Dependencies
      run: |
        cd Bank
        xcodebuild -resolvePackageDependencies \
          -project BankApp.xcodeproj \
          -scheme BankApp
          
    - name: Build Project
      run: |
        cd Bank
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=${{ env.IOS_SIMULATOR_VERSION }}' \
          -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
          -configuration Debug \
          clean build \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          ONLY_ACTIVE_ARCH=YES \
          -verbose \
          | tee build.log
          
    - name: Check for Build Issues
      if: failure()
      run: |
        cd Bank
        echo "=== BUILD FAILED - Analyzing Issues ==="
        if [ -f build.log ]; then
          echo "=== Complete Build Errors ==="
          grep -A 5 -B 5 "error:" build.log || true
          echo ""
          echo "=== SQLite Expression Errors ==="
          grep -n "missing argument label" build.log || true
          echo ""
          echo "=== Type Inference Errors ==="
          grep -n "could not be inferred" build.log || true
          echo ""
          echo "=== Swift Compilation Errors ==="
          grep -n "Swift compilation failed" build.log || true
          echo ""
          echo "=== Last 100 lines of build log ==="
          tail -100 build.log
        fi
        
        echo ""
        echo "=== Checking source files for remaining issues ==="
        cd BankApp
        for file in *.swift; do
          if [ -f "$file" ]; then
            echo "--- $file ---"
            grep -n "Expression<" "$file" | head -5 || true
          fi
        done
        
    - name: Advanced SQLite Fixes (if build failed)
      if: failure()
      run: |
        cd Bank/BankApp
        echo "Applying advanced SQLite.swift fixes..."
        
        # More comprehensive Expression fixes with column name constructors
        for file in *.swift; do
          if [ -f "$file" ]; then
            echo "Advanced processing $file..."
            
            # Alternative approach - use column name string directly in subscript
            # Replace Expression usage patterns with direct column access
            sed -i '' 's/account\[accountIdExpression\]/account[Column("account_id")]/g' "$file"
            sed -i '' 's/account\[accountTypeExpression\]/account[Column("account_type")]/g' "$file"
            sed -i '' 's/account\[balanceExpression\]/account[Column("balance")]/g' "$file"
            sed -i '' 's/account\[overdraftLimitExpression\]/account[Column("overdraft_limit")]/g' "$file"
            sed -i '' 's/account\[username\]/account[Column("username")]/g' "$file"
            sed -i '' 's/user\[user_id\]/user[Column("user_id")]/g' "$file"
            sed -i '' 's/user\[blocked\]/user[Column("is_blocked")]/g' "$file"
            
            # Fix String conversion issues
            sed -i '' 's/String(describing: account\[/String(account[/g' "$file"
            
            echo "Advanced fixes applied to $file"
          fi
        done
        
    - name: Pre-build SQLite Expression Fixes
      run: |
        cd Bank/BankApp
        echo "Applying SQLite.swift syntax fixes before build..."
        
        # Create backup of original files
        find . -name "*.swift" -exec cp {} {}.backup \;
        
        # Fix all Swift files with SQLite Expression syntax issues
        for file in *.swift; do
          if [ -f "$file" ]; then
            echo "Processing $file..."
            
            # Fix Expression initializers - handle all common patterns
            sed -i '' 's/Expression<String>("\([^"]*\)")/Expression<String>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<String?>("\([^"]*\)")/Expression<String?>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Int64>("\([^"]*\)")/Expression<Int64>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Double>("\([^"]*\)")/Expression<Double>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Double?>("\([^"]*\)")/Expression<Double?>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Bool>("\([^"]*\)")/Expression<Bool>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Int>("\([^"]*\)")/Expression<Int>(value: "\1")/g' "$file"
            
            # Fix potential type inference issues with explicit casting
            sed -i '' 's/String(account\[\([^]]*\)\])/String(describing: account[\1])/g' "$file"
            sed -i '' 's/account\[\([^]]*\)\]!/account[\1] ?? ""/g' "$file"
            
            echo "Applied fixes to $file"
          fi
        done
        
        echo "SQLite.swift syntax fixes completed"
        
    - name: Retry Build After Fixes
      if: failure()
      run: |
        cd Bank
        echo "Retrying build after applying advanced fixes..."
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=${{ env.IOS_SIMULATOR_VERSION }}' \
          -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
          -configuration Debug \
          clean build \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          ONLY_ACTIVE_ARCH=YES \
          -verbose \
          | tee retry-build.log
          
    - name: Final Error Analysis (if still failing)
      if: failure()
      run: |
        cd Bank
        echo "=== FINAL BUILD FAILURE ANALYSIS ==="
        if [ -f retry-build.log ]; then
          echo "=== Retry Build Errors ==="
          grep -A 10 -B 5 "error:" retry-build.log | tail -50
        fi
        
        echo ""
        echo "=== Current source file state ==="
        cd BankApp
        for file in ViewControllerAccount.swift ViewControllerAccounts.swift; do
          if [ -f "$file" ]; then
            echo "--- Content of $file (first 30 lines) ---"
            head -30 "$file"
            echo ""
          fi
        done
          
    - name: Run Unit Tests
      run: |
        cd Bank
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=${{ env.IOS_SIMULATOR_VERSION }}' \
          -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
          test \
          -only-testing:BankAppTests \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          -resultBundlePath build/reports/unit-tests.xcresult \
          | tee unit-test.log
          
    - name: Run UI Tests
      run: |
        cd Bank
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=${{ env.IOS_SIMULATOR_VERSION }}' \
          -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
          test \
          -only-testing:BankAppUITests \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          -resultBundlePath build/reports/ui-tests.xcresult \
          | tee ui-test.log
          
    - name: Generate Test Report
      if: always()
      run: |
        cd Bank
        echo "=== TEST SUMMARY ==="
        if [ -f unit-test.log ]; then
          echo "Unit Tests Results:"
          grep -E "(Test Suite|Test Case.*passed|Test Case.*failed|Executed.*tests)" unit-test.log | tail -10
        fi
        if [ -f ui-test.log ]; then
          echo "UI Tests Results:"
          grep -E "(Test Suite|Test Case.*passed|Test Case.*failed|Executed.*tests)" ui-test.log | tail -10
        fi
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: Bank/build/reports/
        retention-days: 30
        
    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          Bank/build.log
          Bank/unit-test.log  
          Bank/ui-test.log
        retention-days: 7
        
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports
        path: ${{ env.DERIVED_DATA_PATH }}/*/Logs/Test/*.xcresult
        retention-days: 30

  build-release:
    name: Build Release
    runs-on: macos-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 30
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
        
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ${{ env.DERIVED_DATA_PATH }}
        key: ${{ runner.os }}-xcode-${{ env.XCODE_VERSION }}-derived-data-${{ hashFiles('**/BankApp.xcodeproj/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-${{ env.XCODE_VERSION }}-derived-data-
          
    - name: Fix Deployment Target for Release
      run: |
        cd Bank
        sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 18.4/IPHONEOS_DEPLOYMENT_TARGET = 18.2/g' BankApp.xcodeproj/project.pbxproj || true
        
    - name: Apply SQLite Fixes for Release
      run: |
        cd Bank/BankApp
        
        # Apply comprehensive SQLite fixes for release build
        for file in *.swift; do
          if [ -f "$file" ]; then
            # Fix Expression initializers with value parameter
            sed -i '' 's/Expression<String>("\([^"]*\)")/Expression<String>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<String?>("\([^"]*\)")/Expression<String?>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Int64>("\([^"]*\)")/Expression<Int64>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Double>("\([^"]*\)")/Expression<Double>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Double?>("\([^"]*\)")/Expression<Double?>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Bool>("\([^"]*\)")/Expression<Bool>(value: "\1")/g' "$file"
            sed -i '' 's/Expression<Int>("\([^"]*\)")/Expression<Int>(value: "\1")/g' "$file"
            
            # Fix column access patterns
            sed -i '' 's/account\[accountIdExpression\]/account[Column("account_id")]/g' "$file"
            sed -i '' 's/account\[accountTypeExpression\]/account[Column("account_type")]/g' "$file"
            sed -i '' 's/account\[balanceExpression\]/account[Column("balance")]/g' "$file"
            sed -i '' 's/account\[overdraftLimitExpression\]/account[Column("overdraft_limit")]/g' "$file"
            sed -i '' 's/account\[username\]/account[Column("username")]/g' "$file"
            sed -i '' 's/user\[user_id\]/user[Column("user_id")]/g' "$file"
            sed -i '' 's/user\[blocked\]/user[Column("is_blocked")]/g' "$file"
          fi
        done
        
    - name: Build for Release
      run: |
        cd Bank
        set -o pipefail
        xcodebuild -project BankApp.xcodeproj \
          -scheme BankApp \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
          clean build \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          ONLY_ACTIVE_ARCH=NO
          
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-build
        path: ${{ env.DERIVED_DATA_PATH }}/Build/Products/Release-iphoneos/
        retention-days: 90
