name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-deriveddata-${{ hashFiles('**/BankApp.xcodeproj/project.pbxproj') }}
          restore-keys: |
            ${{ runner.os }}-deriveddata-

      - name: Install dependencies
        run: |
          cd Bank
          echo "Installing dependencies..."
          # Or if using Swift Package Manager, dependencies are resolved automatically

      - name: Check Build Issues
        run: |
          cd Bank
          echo "Attempting to build project to identify issues..."
          xcodebuild -project BankApp.xcodeproj \
            -scheme BankApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            clean build \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" || echo "Build failed - continuing with available information"

      - name: Build and Test
        run: |
          cd Bank
          set -o pipefail
          xcodebuild -project BankApp.xcodeproj \
            -scheme BankApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            clean build test \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Run Unit Tests
        run: |
          cd Bank
          set -o pipefail
          xcodebuild -project BankApp.xcodeproj \
            -scheme BankApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            test -only-testing:BankAppTests \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Run UI Tests
        run: |
          cd Bank
          set -o pipefail
          xcodebuild -project BankApp.xcodeproj \
            -scheme BankApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            test -only-testing:BankAppUITests \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            Bank/BankAppTests/*.xcresult
            Bank/BankAppUITests/*.xcresult

      - name: Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: Bank/*.xcresult
